//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiclose.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quiclose.Localization.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name:.
        /// </summary>
        public static string Main_AppName_Label {
            get {
                return ResourceManager.GetString("Main_AppName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for app.
        /// </summary>
        public static string Main_CheckRunning_Button {
            get {
                return ResourceManager.GetString("Main_CheckRunning_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind:.
        /// </summary>
        public static string Main_Keybind_Label {
            get {
                return ResourceManager.GetString("Main_Keybind_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num /.
        /// </summary>
        public static string VK_Label_DIVIDE {
            get {
                return ResourceManager.GetString("VK_Label_DIVIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F11.
        /// </summary>
        public static string VK_Label_F11 {
            get {
                return ResourceManager.GetString("VK_Label_F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause | Break.
        /// </summary>
        public static string VK_Label_PAUSE {
            get {
                return ResourceManager.GetString("VK_Label_PAUSE", resourceCulture);
            }
        }
    }
}
